# Site settings
title: Otro blog del monton
email: pigant666@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Apuntes propios, acerca de temas de programación en general
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pigant.github.io" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
#twitter_username: none
github_username:  pigant

# Build settings
markdown: kramdown

exclude: [ruby]
